return
-- SUPERMAVEN
-- {
--   'supermaven-inc/supermaven-nvim',
--   config = function()
--     require('supermaven-nvim').setup {
--       keymaps = {
--         accept_suggestion = '<C-g>',
--         clear_suggestion = '<C-z>',
--         accept_word = '<C-b>',
--       },
--       ignore_filetypes = {}, -- or { "cpp", }
--       color = {
--         suggestion_color = '#536555',
--       },
--       disable_keymaps = false, -- disables built in keymaps for more manual control
--       condition = function()
--         return false
--       end, -- condition to check for stopping supermaven, `true` means to stop supermaven when the condition is true.
--     }
--   end,
-- }
{}
